"""Add column

Revision ID: 00f92b7899bb
Revises: 4429573f84a4
Create Date: 2025-03-06 12:43:55.708320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f92b7899bb'
down_revision = '4429573f84a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movers', sa.Column('image', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image')
    op.drop_column('movers', 'image')
    # ### end Alembic commands ###
