"""change image column in inventory

Revision ID: 113515cc46a1
Revises: 00f92b7899bb
Create Date: 2025-03-07 07:40:10.499875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113515cc46a1'
down_revision = '00f92b7899bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory', 'image',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=900),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory', 'image',
               existing_type=sa.String(length=900),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
