"""Add distance column

Revision ID: 2d65025861eb
Revises: d4dfe50f744e
Create Date: 2025-03-06 01:31:26.907725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d65025861eb'
down_revision = 'd4dfe50f744e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moves', sa.Column('distance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moves', 'distance')
    # ### end Alembic commands ###
