"""Forgot password

Revision ID: 365a1027d3d7
Revises: 64feb0c73875
Create Date: 2025-02-27 22:58:52.646614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365a1027d3d7'
down_revision = '64feb0c73875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('reset_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_expires_at')
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
