"""updates

Revision ID: 4429573f84a4
Revises: 2d65025861eb
Create Date: 2025-03-06 04:07:00.839144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4429573f84a4'
down_revision = '2d65025861eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('image', sa.String(length=100), nullable=True))
    op.drop_column('inventory', 'category')
    op.add_column('inventory_users', sa.Column('priority', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_users', 'priority')
    op.add_column('inventory', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('inventory', 'image')
    # ### end Alembic commands ###
