"""Initial Migration

Revision ID: 48cb3550e760
Revises: 9963a8d27d81
Create Date: 2025-02-22 09:07:35.539120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48cb3550e760'
down_revision = '9963a8d27d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'movers', ['user_id'])
    op.create_foreign_key(op.f('fk_movers_user_id_users'), 'movers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_movers_user_id_users'), 'movers', type_='foreignkey')
    op.drop_constraint(None, 'movers', type_='unique')
    op.drop_column('movers', 'user_id')
    # ### end Alembic commands ###
