"""Add otp columns

Revision ID: 64feb0c73875
Revises: b6b96ed77208
Create Date: 2025-02-27 17:51:19.874866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64feb0c73875'
down_revision = 'b6b96ed77208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'otp_code')
    # ### end Alembic commands ###
