"""Add house type to users table

Revision ID: b6b96ed77208
Revises: e88a24681377
Create Date: 2025-02-24 19:54:23.249778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6b96ed77208'
down_revision = 'e88a24681377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('house_type', sa.String(length=100), server_default='None', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'house_type')
    # ### end Alembic commands ###
