"""Initial Migration

Revision ID: e88a24681377
Revises: 48cb3550e760
Create Date: 2025-02-22 09:09:05.138383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e88a24681377'
down_revision = '48cb3550e760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movers_user_id_key', 'movers', type_='unique')
    op.drop_constraint('fk_movers_user_id_users', 'movers', type_='foreignkey')
    op.drop_column('movers', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movers', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_movers_user_id_users', 'movers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('movers_user_id_key', 'movers', ['user_id'])
    # ### end Alembic commands ###
